#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	2
bspc config window_gap          	4

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true
bspc config pointer_motion_interval	60
bspc config click_to_focus		any
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
