#!/usr/bin/env sh

num_mons=`xrandr -q | grep " connected" | wc -l`

if [[ $num_mons > 1 ]]
then
  if [[ $1 == "-s" ]]
  then
    echo "m"
  else
    echo "monitor"
  fi
else
  if [[ $1 == "-s" ]]
  then
    echo "d"
  else
    echo "desktop"
  fi
fi
